- name: "install dependencies."
  apt:
    pkg: 
      - npm
      - pm2
      - tar
    state: latest
    update_cache: true

- name: "upload backend code artifact."
  copy:
    src: artifact.tar.gz
    dest: ~/web/

- name: "install and start backend."
  shell:
    cmd: |
      cd ~/web
      tar -xvzf artifact.tar.gz
      ls -la
      npm install
      pm2 stop default
      pm2 start npm -- start
